[project]
name = "portfolio"
version = "1.0.0"
description = "Portfolio personal en Reflex"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"
dependencies = [
    "reflex>=0.8.20",
]

[tool.mypy]
    files = ["portfolio/"]  # Rutas a analizar
    # ignore_missing_imports = true  # Ignorar errores por módulos no encontrados
    strict = false  # Activar modo estricto

[tool.pyrefly]
project-includes = ["portfolio/"]

